# Generated by Django 5.0.2 on 2025-06-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_alter_post_title_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
